author: GitHub User
name: Your Username

title: Hyun Jun Yook
description: >- # this means to ignore newlines until "baseurl:"
  HYUN JUN YOOK received the B.E. degree in control and instrumentation engineering from 
  Korea University, Sejong, Republic of Korea. He is currently pursuing the M.S. degree in 
  computer engineering with Hongik University, Seoul, Republic of Korea. His research interests 
  include deep learning, computer vision, and multimodal learning.

email: hyunjunyook@g.hongik.ac.kr

# social links
twitter_username: anxhe_
github_username:  p6trick
# rss: rss
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# baseurl: http://127.0.0.1:4000
header_pages:
  - index.md
  - papers.md
  - projects.md
  - patents.md

# Config section the home


# Build settings
markdown: kramdown

jekyll-theme-experiment:
  about:
    avatar : /assets/hj.png #https://robohash.org/experiment-avatar.png?size=300x300

  portfolio:
    title: Portfolio
    projects:

      - name: Papers
        github: https://p6trick.github.io/papers.html
        img_relative_url: /assets/example.png

      - name: Projects
        github: https://p6trick.github.io/projects.html
        img_relative_url: /assets/example.png

      - name: Patents
        github: https://p6trick.github.io/patents.html
        img_relative_url: /assets/example.png



  tools:
    title: Tools and Experience
    icons:
      - relative_url: https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg
      - relative_url: https://upload.wikimedia.org/wikipedia/commons/1/10/PyTorch_logo_icon.svg
      - relative_url: https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg
      - relative_url: https://upload.wikimedia.org/wikipedia/commons/9/92/LaTeX_logo.svg
      - relative_url: /assets/icons/git/git-original.svg
      

exclude:
  - Gemfile
  - Gemfile.lock
